spring:
  datasource:
    url: jdbc:h2:mem:lunch-orderer
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
  h2:
    console.enabled: true