spring:
  datasource:
    url: jdbc:h2:mem:lunch-orderer
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console.enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "smtp.lunch.orderer@gmail.com"
    password: "ywac knuf qaig khwq"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

hr.leapwise.lunchorderer:
  order:
    email: "nikola.tovernic@hotmail.com"
    cron: "0 30 10 * * *"